src/Entity/Etape.php
<?php

namespace App\Entity;

use App\Repository\EtapeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapeRepository::class)]
class Etape
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $texte_ambiance = null;

    #[ORM\Column(length: 255)]
    private ?string $libelle = null;

    #[ORM\OneToOne(mappedBy: 'premiereEtape', cascade: ['persist', 'remove'])]
    private ?Aventure $aventureDebutee = null;

    #[ORM\ManyToOne(inversedBy: 'etapes')]
    private ?aventure $aventure = null;

    #[ORM\ManyToOne(inversedBy: 'finsPossibles')]
    private ?aventure $finAventure = null;

    /**
     * @var Collection<int, Alternative>
     */
    #[ORM\OneToMany(targetEntity: Alternative::class, mappedBy: 'etapePrecedente')]
    private Collection $Alternatives;

    /**
     * @var Collection<int, Partie>
     */
    #[ORM\OneToMany(targetEntity: Partie::class, mappedBy: 'etape')]
    private Collection $parties;

    public function __construct()
    {
        $this->Alternatives = new ArrayCollection();
        $this->parties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTexteAmbiance(): ?string
    {
        return $this->texte_ambiance;
    }

    public function setTexteAmbiance(string $texte_ambiance): static
    {
        $this->texte_ambiance = $texte_ambiance;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): static
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getAventureDebutee(): ?Aventure
    {
        return $this->aventureDebutee;
    }

    public function setAventureDebutee(?Aventure $aventureDebutee): static
    {
        // unset the owning side of the relation if necessary
        if ($aventureDebutee === null && $this->aventureDebutee !== null) {
            $this->aventureDebutee->setPremiereEtape(null);
        }

        // set the owning side of the relation if necessary
        if ($aventureDebutee !== null && $aventureDebutee->getPremiereEtape() !== $this) {
            $aventureDebutee->setPremiereEtape($this);
        }

        $this->aventureDebutee = $aventureDebutee;

        return $this;
    }

    public function getAventure(): ?aventure
    {
        return $this->aventure;
    }

    public function setAventure(?aventure $aventure): static
    {
        $this->aventure = $aventure;

        return $this;
    }

    public function getFinAventure(): ?aventure
    {
        return $this->finAventure;
    }

    public function setFinAventure(?aventure $finAventure): static
    {
        $this->finAventure = $finAventure;

        return $this;
    }

    /**
     * @return Collection<int, Alternative>
     */
    public function getAlternatives(): Collection
    {
        return $this->Alternatives;
    }

    public function addAlternative(Alternative $alternative): static
    {
        if (!$this->Alternatives->contains($alternative)) {
            $this->Alternatives->add($alternative);
            $alternative->setEtapePrecedente($this);
        }

        return $this;
    }

    public function removeAlternative(Alternative $alternative): static
    {
        if ($this->Alternatives->removeElement($alternative)) {
            // set the owning side to null (unless already changed)
            if ($alternative->getEtapePrecedente() === $this) {
                $alternative->setEtapePrecedente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Partie>
     */
    public function getParties(): Collection
    {
        return $this->parties;
    }

    public function addParty(Partie $party): static
    {
        if (!$this->parties->contains($party)) {
            $this->parties->add($party);
            $party->setEtape($this);
        }

        return $this;
    }

    public function removeParty(Partie $party): static
    {
        if ($this->parties->removeElement($party)) {
            // set the owning side to null (unless already changed)
            if ($party->getEtape() === $this) {
                $party->setEtape(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->libelle;
    }
}

src/Controller/JouerController.php
<?php

namespace App\Controller;

use App\Util\Utils;
use App\Entity\Etape;
use App\Entity\Personnage;
use App\Entity\Partie;
use App\Form\PersonnageType;
use App\Repository\AlternativeRepository;
use App\Repository\PersonnageRepository;
use App\Repository\AventureRepository;
use App\Repository\EtapeRepository;
use App\Repository\PartieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;


class JouerController extends AbstractController
{
    #[Route('/jouer', name: 'app_jouer')]
    public function index(PersonnageRepository $personnageRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnages = $personnageRepository->findBy(["user"=>$this->getUser()]);
        return $this->render('jouer/index.html.twig', [
            'personnages' => $personnages
        ]);
    }

    #[Route('/jouer/new', name: 'app_jouer_new')]
    public function newPersonnage(Request $request, EntityManagerInterface $entityManager)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = new Personnage();
        $form = $this->createForm(PersonnageType::class, $personnage);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $personnage->setUser($this->getUser());
            $entityManager->persist($personnage);
            $entityManager->flush();
            return $this->redirectToRoute('app_jouer', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('jouer/new_personnage.html.twig', ['form'=>$form, 'personnage'=>$personnage]);
    }

    #[Route('jouer/aventures/{idPersonnage}', name: 'app_choix_aventure', methods:['GET'])]
    public function afficherAventures(PersonnageRepository $personnageRepository, AventureRepository $aventureRepository, $idPersonnage):Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = $personnageRepository->find($idPersonnage);
        if ($personnage->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException("You do not have access to this character");
        }
        $aventures = $aventureRepository->findAll();
        return $this->render('jouer/aventures.html.twig', ['personnage' => $personnage , 'aventures' => $aventures]);
    }

    #[Route('jouer/aventure/{idPersonnage}/{idAventure}', name: 'app_start_aventure', methods: ['GET'])]
    public function demarrerAventure(PersonnageRepository $personnageRepository, AventureRepository $aventureRepository, PartieRepository $partieRepository, EntityManagerInterface $entityManager, $idPersonnage, $idAventure, ):Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $personnage = $personnageRepository->find($idPersonnage);
        if ($personnage->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException("You do not have access to this character");
        }
        $aventure = $aventureRepository->find($idAventure);
        $partie = $partieRepository->findOneBy(array('aventurier'=>$personnage,'aventure'=>$aventure));
        $isNewPartie = !isset($partie);
        if ($isNewPartie)
        {
            $isNewPartie = true;
            $partie = new Partie();
            $partie->setAventurier($personnage);
            $partie->setAventure($aventure);
            $partie->setEtape($aventure->getPremiereEtape());
            $partie->setDatePartie(new \DateTime('now'));
            $entityManager->persist($partie);
            $entityManager->flush();
        }
        return $this->render('jouer/aventure-start.html.twig', ['personnage'=>$personnage,'aventure'=>$aventure, 'partie'=>$partie]);
    }

    #[Route('jouer/etape/{idPartie}/{idEtape}', name: 'app_play_aventure', methods: ['GET'])]
    public function jouerAventure(PartieRepository $partieRepository, EtapeRepository $etapeRepository,AlternativeRepository $alternativeRepository, $idPartie, $idEtape,EntityManagerInterface $entityManager)
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $partie = $partieRepository->find($idPartie);
        if ($partie->getAventurier()->getUser() !== $this->getUser()) {
            throw $this->createAccessDeniedException('You do not have access to this partie!');
        }
        $etape = $etapeRepository->find($idEtape);   
        $partie->setEtape($etape); 
        $entityManager->persist($partie);
        $entityManager->flush();
        if ($etape->getFinAventure() != null) {
            return $this->render('jouer/aventure-end.html.twig', ['partie' => $partie]);
        } else {
            return $this->render('jouer/aventure-play.html.twig', ['partie' => $partie]);
        }
    }
}

templates/jouer/aventure-end.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
    <div class="row bg-dark text-white">
        <div class="col-md-8">
            <p>{{ partie.etape.texteAmbiance }}</p>
            <div>Ceci est la (une ?) fin de l'aventure ! Bien joué ! Ou pas !</div>
            <a href="{{ path('app_jouer', {'idPartie': partie.id , 'idEtape': partie.etape.id}) }}" class="btn btn-primary">Jouer</a>
        </div>
    </div>
</div>
{% endblock %}

templates/jouer/aventure-play.html.twig
{% extends 'base.html.twig' %}

{% block title %} L'Aventure continue... {% endblock %}

{% block body %}

<div class="bg-white" style="--bs-bg-opacity: .75;">{{partie.etape.texteAmbiance}}</div>
<div class="row bg-white" style="--bs-bg-opacity: .75;">
{% for alternative in partie.etape.alternatives %}
<div class="col">
<div style="display: inline-block; vertical-align: top;"> {{alternative.texteAmbiance}} </div>
<a class="btn btn-link" style="vertical-align: top;" href="{{ path('app_play_aventure', {'idPartie': partie.id , 'idEtape': alternative.etapeSuivante.id}) }}"> Cliquez ici </a>
</div>
{% endfor %}
</div>
{% endblock %}

templates/jouer/aventure-start.html.twig
{% extends 'base.html.twig' %}

{% block title %}Le début de l'aventure {% endblock %}

{% block body %}
<div class="container">
    <div class="card bg-dark text-white">
        <div class="card-body">
            <p class="card-text">Le personnage {{ personnage.prenom }} commence l'aventure {{ aventure.titre }} !</p>
            <a href="{{ path('app_play_aventure', {'idPartie': partie.id, 'idEtape': partie.etape.id}) }}" class="btn btn-primary">Lancer</a>
        </div>
    </div>
</div>
{% endblock %}

templates/jouer/aventures.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des aventures {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4">
        <div class="card mb-3">
            <img src="{{ asset('images/avatars/' ~ personnage.avatar.getNomFichier()) }}" class="card-img-top" alt="Avatar">
            <div class="card-body">
                <h5 class="card-title">{{ personnage.prenom }}</h5>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        {% for aventure in aventures %}
<div class="card mb-3 bg-dark">
    <div class="card-body">
        <h5 class="card-title text-white">{{ aventure.titre }}</h5>
        <p class="card-text text-white">{{ aventure.description }}</p>
        <a href="{{ path('app_start_aventure', {'idPersonnage': personnage.id, 'idAventure': aventure.id }) }}" class="btn btn-primary">Jouer</a>
    </div>
</div>
        {% else %}
        <p>Aucune aventure</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/jouer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JouerController!{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
{% for personnage in personnages %}
    <div class="col-md-3 mb-3">
        <div class="card">
        {% set values = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f']%}
        <div style="background: radial-gradient(circle, #{{random(values)~ random(values)~ random(values)~ random(values)~ random(values)~ random(values)}}, black);">
            <a href="{{ path('app_choix_aventure', {'idPersonnage': personnage.id}) }}">
                <img src="{{ asset('images/avatars/' ~ personnage.avatar.getNomFichier()) }}" class="card-img-top" alt="Avatar">
                <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ personnage.prenom }}</h5>
                </div>
                </div>
            </a>
        </div>
        </div>
    </div>
{% else %}
    <div class="card" class="col">
        Aucun personnage trouvé
    </div>
{% endfor %}
    </div>
    <div class="row mt-3">
        <a href="/jouer/new" class="btn btn-primary">Créer</a>
    </div>
</div>
{% endblock %}

templates/jouer/new_personnage.html.twig
{% extends 'base.html.twig' %}

{% block title %} NOUVEAU PERSONNAGE {% endblock %}

{% block body %}
<div class="card" style="padding: 10px;">
{{form_start(form)}}
{{form_widget(form)}}
<button>Créer</button>
{{form_end(form)}}
</div>
{% endblock %}