src/Entity/Avatar.php
<?php

namespace App\Entity;

use App\Repository\AvatarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvatarRepository::class)]
class Avatar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_fichier = null;

    /**
     * @var Collection<int, Personnage>
     */
    #[ORM\OneToMany(targetEntity: Personnage::class, mappedBy: 'avatar')]
    private Collection $personnages;

    public function __construct()
    {
        $this->personnages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomFichier(): ?string
    {
        return $this->nom_fichier;
    }

    public function setNomFichier(string $nom_fichier): static
    {
        $this->nom_fichier = $nom_fichier;

        return $this;
    }

    /**
     * @return Collection<int, Personnage>
     */
    public function getPersonnages(): Collection
    {
        return $this->personnages;
    }

    public function addPersonnage(Personnage $personnage): static
    {
        if (!$this->personnages->contains($personnage)) {
            $this->personnages->add($personnage);
            $personnage->setAvatar($this);
        }

        return $this;
    }

    public function removePersonnage(Personnage $personnage): static
    {
        if ($this->personnages->removeElement($personnage)) {
            // set the owning side to null (unless already changed)
            if ($personnage->getAvatar() === $this) {
                $personnage->setAvatar(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom_fichier;
    }
}

src/Form/AvatarType.php
<?php

namespace App\Form;

use App\Entity\Avatar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvatarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_fichier')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avatar::class,
        ]);
    }
}

src/Controller/AvatarController.php
<?php

namespace App\Controller;

use App\Entity\Avatar;
use App\Form\AvatarType;
use App\Repository\AvatarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/avatar')]
class AvatarController extends AbstractController
{
    #[Route('/', name: 'app_avatar_index', methods: ['GET'])]
    public function index(AvatarRepository $avatarRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('avatar/index.html.twig', [
            'avatars' => $avatarRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_avatar_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $avatar = new Avatar();
        $form = $this->createForm(AvatarType::class, $avatar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avatar);
            $entityManager->flush();

            return $this->redirectToRoute('app_avatar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avatar/new.html.twig', [
            'avatar' => $avatar,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avatar_show', methods: ['GET'])]
    public function show(Avatar $avatar): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('avatar/show.html.twig', [
            'avatar' => $avatar,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_avatar_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Avatar $avatar, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $form = $this->createForm(AvatarType::class, $avatar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_avatar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avatar/edit.html.twig', [
            'avatar' => $avatar,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avatar_delete', methods: ['POST'])]
    public function delete(Request $request, Avatar $avatar, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete'.$avatar->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($avatar);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_avatar_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/avatar/_delete_form.html.twig
<form method="post" action="{{ path('app_avatar_delete', {'id': avatar.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avatar.id) }}">
    <button class="btn">Delete</button>
</form>

templates/avatar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/avatar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Avatar{% endblock %}

{% block body %}
    <h1 class="card">Edit Avatar</h1>

    {{ include('avatar/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="card" href="{{ path('app_avatar_index') }}">back to list</a>

    {{ include('avatar/_delete_form.html.twig') }}
{% endblock %}

templates/avatar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avatar index{% endblock %}

{% block body %}
    <h1 class="card">Avatar index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_fichier</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for avatar in avatars %}
            <tr>
                <td>{{ avatar.id }}</td>
                <td>{{ avatar.nomFichier }}</td>
                <td>
                    <a href="{{ path('app_avatar_show', {'id': avatar.id}) }}">show</a>
                    <a href="{{ path('app_avatar_edit', {'id': avatar.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="card" href="{{ path('app_avatar_new') }}">Create new</a>
{% endblock %}

templates/avatar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Avatar{% endblock %}

{% block body %}
    <h1 class="card">Create new Avatar</h1>

    {{ include('avatar/_form.html.twig') }}

    <a class="card" href="{{ path('app_avatar_index') }}">back to list</a>
{% endblock %}

templates/avatar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avatar{% endblock %}

{% block body %}
    <h1 class="card">Avatar</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avatar.id }}</td>
            </tr>
            <tr>
                <th>Nom_fichier</th>
                <td>{{ avatar.nomFichier }}</td>
            </tr>
        </tbody>
    </table>

    <a class="card" href="{{ path('app_avatar_index') }}">back to list</a>

    <a class="card" href="{{ path('app_avatar_edit', {'id': avatar.id}) }}">edit</a>

    {{ include('avatar/_delete_form.html.twig') }}
{% endblock %}