src/Entity/Partie.php
<?php

namespace App\Entity;

use App\Repository\PartieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartieRepository::class)]
class Partie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_partie = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Personnage $aventurier = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Aventure $aventure = null;

    #[ORM\ManyToOne(inversedBy: 'parties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Etape $etape = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePartie(): ?\DateTimeInterface
    {
        return $this->date_partie;
    }

    public function setDatePartie(\DateTimeInterface $date_partie): static
    {
        $this->date_partie = $date_partie;

        return $this;
    }

    public function getAventurier(): ?Personnage
    {
        return $this->aventurier;
    }

    public function setAventurier(?Personnage $aventurier): static
    {
        $this->aventurier = $aventurier;

        return $this;
    }

    public function getAventure(): ?Aventure
    {
        return $this->aventure;
    }

    public function setAventure(?Aventure $aventure): static
    {
        $this->aventure = $aventure;

        return $this;
    }

    public function getEtape(): ?Etape
    {
        return $this->etape;
    }

    public function setEtape(?Etape $etape): static
    {
        $this->etape = $etape;

        return $this;
    }
    public function __toString()
    {
        return $this->aventure->getTitre();
    }
}

src/Form/PartieType.php
<?php

namespace App\Form;

use App\Entity\Aventure;
use App\Entity\Etape;
use App\Entity\Partie;
use App\Entity\Personnage;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PartieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_partie', null, [
                'widget' => 'single_text',
            ])
            ->add('aventurier', EntityType::class, [
                'class' => Personnage::class,
                'choice_label' => 'id',
            ])
            ->add('aventure', EntityType::class, [
                'class' => Aventure::class,
                'choice_label' => 'id',
            ])
            ->add('etape', EntityType::class, [
                'class' => Etape::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Partie::class,
        ]);
    }
}

src/Controller/PartieController.php
<?php

namespace App\Controller;

use App\Entity\Partie;
use App\Form\PartieType;
use App\Repository\PartieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/partie')]
class PartieController extends AbstractController
{
    #[Route('/', name: 'app_partie_index', methods: ['GET'])]
    public function index(PartieRepository $partieRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('partie/index.html.twig', [
            'parties' => $partieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_partie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $partie = new Partie();
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($partie);
            $entityManager->flush();

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('partie/new.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_show', methods: ['GET'])]
    public function show(Partie $partie): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        return $this->render('partie/show.html.twig', [
            'partie' => $partie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_partie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Partie $partie, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        $form = $this->createForm(PartieType::class, $partie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('partie/edit.html.twig', [
            'partie' => $partie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_partie_delete', methods: ['POST'])]
    public function delete(Request $request, Partie $partie, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete'.$partie->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($partie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_partie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/partie/_delete_form.html.twig
<form method="post" action="{{ path('app_partie_delete', {'id': partie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ partie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/partie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/partie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Partie{% endblock %}

{% block body %}
    <h1 class="card">Edit Partie</h1>

    {{ include('partie/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="card" href="{{ path('app_partie_index') }}">back to list</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}

templates/partie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie index{% endblock %}

{% block body %}
    <div class="card"><h1>Partie index</h1></div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date_partie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for partie in parties %}
            <tr>
                <td>{{ partie.id }}</td>
                <td>{{ partie.datePartie ? partie.datePartie|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_partie_show', {'id': partie.id}) }}">show</a>
                    <a href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="card" href="{{ path('app_partie_new') }}">Create new</a>
{% endblock %}

templates/partie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Partie{% endblock %}

{% block body %}
    <h1 class="card">Create new Partie</h1>

    {{ include('partie/_form.html.twig') }}

    <a class="card" href="{{ path('app_partie_index') }}">back to list</a>
{% endblock %}

templates/partie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Partie{% endblock %}

{% block body %}
    <h1 class="card">Partie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ partie.id }}</td>
            </tr>
            <tr>
                <th>Date_partie</th>
                <td>{{ partie.datePartie ? partie.datePartie|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="card" href="{{ path('app_partie_index') }}">back to list</a>

    <a class="card" href="{{ path('app_partie_edit', {'id': partie.id}) }}">edit</a>

    {{ include('partie/_delete_form.html.twig') }}
{% endblock %}